// Generated by https://quicktype.io

import type { z } from "zod"
import type { dataSchema } from "./data"

// export interface Data2 {
//   name: string
//   music: Music
//   background: Background
//   typing: Typing
//   messages: Array<Message>
// }

// export interface Background {
//   topColor: string
//   bottomColor: string
//   type: string
//   starAngle: number
//   starQuantity: number
//   starOpacity: number[]
//   starSize: number[]
// }

// export interface Message {
//   text: string
//   position?: number
//   image?: string
//   type?: string
//   color?: string
// }

// export interface Music {
//   volume: number
//   id: number
//   src: string
//   autoplay: boolean
//   loop: boolean
// }

// export interface Typing {
//   delay: number
//   textColor: string
// }
